# Generated by Django 2.1.7 on 2019-02-18 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name': '概念',
                'verbose_name_plural': '概念',
                'ordering': ['-updated_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
