# Generated by Django 2.1.7 on 2019-02-18 08:39

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='项目')),
                ('value', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True, verbose_name='值')),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
